// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: proto/forwardresprpc.proto

package forwardresprpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ForwardRespRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host                 string `protobuf:"bytes,1,opt,name=Host,proto3" json:"Host,omitempty"`
	StateMachineResponse string `protobuf:"bytes,2,opt,name=StateMachineResponse,proto3" json:"StateMachineResponse,omitempty"`
}

func (x *ForwardRespRequest) Reset() {
	*x = ForwardRespRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_forwardresprpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForwardRespRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardRespRequest) ProtoMessage() {}

func (x *ForwardRespRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forwardresprpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardRespRequest.ProtoReflect.Descriptor instead.
func (*ForwardRespRequest) Descriptor() ([]byte, []int) {
	return file_proto_forwardresprpc_proto_rawDescGZIP(), []int{0}
}

func (x *ForwardRespRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ForwardRespRequest) GetStateMachineResponse() string {
	if x != nil {
		return x.StateMachineResponse
	}
	return ""
}

type ForwardRespResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProcessedRequest bool `protobuf:"varint,1,opt,name=ProcessedRequest,proto3" json:"ProcessedRequest,omitempty"`
}

func (x *ForwardRespResponse) Reset() {
	*x = ForwardRespResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_forwardresprpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForwardRespResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardRespResponse) ProtoMessage() {}

func (x *ForwardRespResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forwardresprpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardRespResponse.ProtoReflect.Descriptor instead.
func (*ForwardRespResponse) Descriptor() ([]byte, []int) {
	return file_proto_forwardresprpc_proto_rawDescGZIP(), []int{1}
}

func (x *ForwardRespResponse) GetProcessedRequest() bool {
	if x != nil {
		return x.ProcessedRequest
	}
	return false
}

var File_proto_forwardresprpc_proto protoreflect.FileDescriptor

var file_proto_forwardresprpc_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x72,
	0x65, 0x73, 0x70, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x66, 0x6f,
	0x72, 0x77, 0x61, 0x72, 0x64, 0x72, 0x65, 0x73, 0x70, 0x72, 0x70, 0x63, 0x22, 0x5c, 0x0a, 0x12,
	0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x14, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x41, 0x0a, 0x13, 0x46, 0x6f,
	0x72, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2a, 0x0a, 0x10, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x50, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x32, 0x71, 0x0a,
	0x12, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x5b, 0x0a, 0x0e, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x52, 0x50, 0x43, 0x12, 0x22, 0x2e, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x72,
	0x65, 0x73, 0x70, 0x72, 0x70, 0x63, 0x2e, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x66, 0x6f, 0x72, 0x77,
	0x61, 0x72, 0x64, 0x72, 0x65, 0x73, 0x70, 0x72, 0x70, 0x63, 0x2e, 0x46, 0x6f, 0x72, 0x77, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x16, 0x5a, 0x14, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72,
	0x64, 0x72, 0x65, 0x73, 0x70, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_forwardresprpc_proto_rawDescOnce sync.Once
	file_proto_forwardresprpc_proto_rawDescData = file_proto_forwardresprpc_proto_rawDesc
)

func file_proto_forwardresprpc_proto_rawDescGZIP() []byte {
	file_proto_forwardresprpc_proto_rawDescOnce.Do(func() {
		file_proto_forwardresprpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_forwardresprpc_proto_rawDescData)
	})
	return file_proto_forwardresprpc_proto_rawDescData
}

var file_proto_forwardresprpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_forwardresprpc_proto_goTypes = []interface{}{
	(*ForwardRespRequest)(nil),  // 0: forwardresprpc.ForwardRespRequest
	(*ForwardRespResponse)(nil), // 1: forwardresprpc.ForwardRespResponse
}
var file_proto_forwardresprpc_proto_depIdxs = []int32{
	0, // 0: forwardresprpc.ForwardRespService.ForwardRespRPC:input_type -> forwardresprpc.ForwardRespRequest
	1, // 1: forwardresprpc.ForwardRespService.ForwardRespRPC:output_type -> forwardresprpc.ForwardRespResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_forwardresprpc_proto_init() }
func file_proto_forwardresprpc_proto_init() {
	if File_proto_forwardresprpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_forwardresprpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForwardRespRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_forwardresprpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForwardRespResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_forwardresprpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_forwardresprpc_proto_goTypes,
		DependencyIndexes: file_proto_forwardresprpc_proto_depIdxs,
		MessageInfos:      file_proto_forwardresprpc_proto_msgTypes,
	}.Build()
	File_proto_forwardresprpc_proto = out.File
	file_proto_forwardresprpc_proto_rawDesc = nil
	file_proto_forwardresprpc_proto_goTypes = nil
	file_proto_forwardresprpc_proto_depIdxs = nil
}
