// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: proto/lerpc.proto

package lerpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	LeaderElectionService_RequestVoteRPC_FullMethodName = "/lerpc.LeaderElectionService/RequestVoteRPC"
)

// LeaderElectionServiceClient is the client API for LeaderElectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LeaderElectionServiceClient interface {
	RequestVoteRPC(ctx context.Context, in *RequestVote, opts ...grpc.CallOption) (*RequestVoteResponse, error)
}

type leaderElectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLeaderElectionServiceClient(cc grpc.ClientConnInterface) LeaderElectionServiceClient {
	return &leaderElectionServiceClient{cc}
}

func (c *leaderElectionServiceClient) RequestVoteRPC(ctx context.Context, in *RequestVote, opts ...grpc.CallOption) (*RequestVoteResponse, error) {
	out := new(RequestVoteResponse)
	err := c.cc.Invoke(ctx, LeaderElectionService_RequestVoteRPC_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LeaderElectionServiceServer is the server API for LeaderElectionService service.
// All implementations must embed UnimplementedLeaderElectionServiceServer
// for forward compatibility
type LeaderElectionServiceServer interface {
	RequestVoteRPC(context.Context, *RequestVote) (*RequestVoteResponse, error)
	mustEmbedUnimplementedLeaderElectionServiceServer()
}

// UnimplementedLeaderElectionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLeaderElectionServiceServer struct {
}

func (UnimplementedLeaderElectionServiceServer) RequestVoteRPC(context.Context, *RequestVote) (*RequestVoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestVoteRPC not implemented")
}
func (UnimplementedLeaderElectionServiceServer) mustEmbedUnimplementedLeaderElectionServiceServer() {}

// UnsafeLeaderElectionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LeaderElectionServiceServer will
// result in compilation errors.
type UnsafeLeaderElectionServiceServer interface {
	mustEmbedUnimplementedLeaderElectionServiceServer()
}

func RegisterLeaderElectionServiceServer(s grpc.ServiceRegistrar, srv LeaderElectionServiceServer) {
	s.RegisterService(&LeaderElectionService_ServiceDesc, srv)
}

func _LeaderElectionService_RequestVoteRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderElectionServiceServer).RequestVoteRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderElectionService_RequestVoteRPC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderElectionServiceServer).RequestVoteRPC(ctx, req.(*RequestVote))
	}
	return interceptor(ctx, in, info, handler)
}

// LeaderElectionService_ServiceDesc is the grpc.ServiceDesc for LeaderElectionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LeaderElectionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lerpc.LeaderElectionService",
	HandlerType: (*LeaderElectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestVoteRPC",
			Handler:    _LeaderElectionService_RequestVoteRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/lerpc.proto",
}
